#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: zijie.zeng.homework.study.model
#数据库连接池
spring:
  datasource:
    username: root
    password: 1203
    url: jdbc:mysql://localhost:3306/sfc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    view:
#      prefix: classpath:/static/